from pathlib import Path

def rep(text, old, new, label):
    if old not in text:
        raise SystemExit('STOP: ' + label + ' does not match the expected baseline.')
    return text.replace(old, new, 1)

path = Path('BleRadar.cpp')
text = path.read_text(encoding='utf-8')
text = rep(text, '    // Passive scan means the badge only listens for advertisements.\n    // It does not transmit scan requests to nearby devices.\n    scanner->setActiveScan(false);\n\n    scanner->setInterval(100);\n', '    // BLE RADAR is user-invoked, so use an active scan here.\n    // This allows scan requests and can retrieve names / extra response data.\n    // Beacon Watch uses its own passive scan functions and remains passive.\n    scanner->setActiveScan(true);\n\n    scanner->setInterval(100);\n', 'BLE RADAR active scan')
path.write_text(text, encoding='utf-8')

path = Path('Display.h')
text = path.read_text(encoding='utf-8')
text = rep(text, '    uint8_t *frameBuffer;\n    int displayTemperature;\n\n    void ClearFrameBuffer();\n', '    uint8_t *frameBuffer;\n    uint8_t *cleanRefreshBuffer;\n\n    int displayTemperature;\n    unsigned refreshCount;\n\n    static constexpr unsigned CleanRefreshInterval = 10;\n\n    void ClearFrameBuffer();\n    void RefreshClean();\n', 'Display cleanup state')
path.write_text(text, encoding='utf-8')

path = Path('Display.cpp')
text = path.read_text(encoding='utf-8')
text = rep(text, 'Display::Display()\n{\n    frameBuffer = nullptr;\n    displayTemperature = 25;\n}\n', 'Display::Display()\n{\n    frameBuffer = nullptr;\n    cleanRefreshBuffer = nullptr;\n\n    displayTemperature = 25;\n    refreshCount = 0;\n}\n', 'Display constructor')
text = rep(text, '    if (frameBuffer == nullptr)\n    {\n        Serial.println("EPD framebuffer allocation failed.");\n        return false;\n    }\n\n    displayTemperature = epd_ambient_temperature();\n', '    if (frameBuffer == nullptr)\n    {\n        Serial.println("EPD framebuffer allocation failed.");\n        return false;\n    }\n\n    const size_t frameBufferBytes =\n        (DisplayLayout::Width *\n         DisplayLayout::Height) /\n        2;\n\n    cleanRefreshBuffer =\n        static_cast<uint8_t *>(\n            ps_malloc(frameBufferBytes));\n\n    if (cleanRefreshBuffer == nullptr)\n    {\n        Serial.println(\n            "EPD clean-refresh buffer unavailable. Periodic clean refresh disabled.");\n    }\n\n    displayTemperature = epd_ambient_temperature();\n', 'Display clean buffer allocation')
text = rep(text, 'void Display::RefreshFull()\n{\n    epd_poweron();\n\n    EpdDrawError error = epd_hl_update_screen(\n        &displayState,\n        MODE_GC16,\n        displayTemperature);\n\n    epd_poweroff();\n\n    if (error != EPD_DRAW_SUCCESS)\n    {\n        Serial.printf(\n            "EPD draw error: %X\\n",\n            static_cast<unsigned>(error));\n    }\n}\n', 'void Display::RefreshFull()\n{\n    refreshCount++;\n\n    if (cleanRefreshBuffer != nullptr &&\n        refreshCount >= CleanRefreshInterval)\n    {\n        refreshCount = 0;\n        RefreshClean();\n        return;\n    }\n\n    epd_poweron();\n\n    EpdDrawError error = epd_hl_update_screen(\n        &displayState,\n        MODE_GC16,\n        displayTemperature);\n\n    epd_poweroff();\n\n    if (error != EPD_DRAW_SUCCESS)\n    {\n        Serial.printf(\n            "EPD draw error: %X\\n",\n            static_cast<unsigned>(error));\n    }\n}\n\nvoid Display::RefreshClean()\n{\n    const size_t frameBufferBytes =\n        (DisplayLayout::Width *\n         DisplayLayout::Height) /\n        2;\n\n    memcpy(\n        cleanRefreshBuffer,\n        frameBuffer,\n        frameBufferBytes);\n\n    Serial.println(\n        "EPD: periodic clean refresh.");\n\n    // Do not use raw epd_clear() here. The high-level EPDiy updater keeps\n    // track of the previous framebuffer. Clearing the physical panel behind\n    // its back would desynchronize that state and can cause later updates to\n    // be skipped incorrectly.\n    //\n    // Instead, first make the high-level framebuffer white and update it.\n    // Then restore the requested page and update again. This gives the panel\n    // a real white cleaning pass while keeping EPDiy\'s diff state correct.\n    epd_hl_set_all_white(\n        &displayState);\n\n    epd_poweron();\n\n    EpdDrawError whiteError =\n        epd_hl_update_screen(\n            &displayState,\n            MODE_GC16,\n            displayTemperature);\n\n    epd_poweroff();\n\n    memcpy(\n        frameBuffer,\n        cleanRefreshBuffer,\n        frameBufferBytes);\n\n    epd_poweron();\n\n    EpdDrawError redrawError =\n        epd_hl_update_screen(\n            &displayState,\n            MODE_GC16,\n            displayTemperature);\n\n    epd_poweroff();\n\n    if (whiteError != EPD_DRAW_SUCCESS)\n    {\n        Serial.printf(\n            "EPD clean white-pass error: %X\\n",\n            static_cast<unsigned>(whiteError));\n    }\n\n    if (redrawError != EPD_DRAW_SUCCESS)\n    {\n        Serial.printf(\n            "EPD clean redraw error: %X\\n",\n            static_cast<unsigned>(redrawError));\n    }\n}\n', 'Periodic clean refresh')
path.write_text(text, encoding='utf-8')

print('Active BLE RADAR + periodic display clean patch applied.')
