from pathlib import Path

def rep(text, old, new, label):
    if old not in text:
        raise SystemExit('STOP: ' + label + ' does not match the expected Beacon Watch baseline.')
    return text.replace(old, new, 1)

path = Path('BadgeConfig.h')
text = path.read_text(encoding='utf-8')
text = rep(text, '    bool BeaconWatchEnabled() const;\n    const char *BeaconAddress() const;\n    int BeaconRssi() const;\n', '    bool BeaconWatchEnabled() const;\n\n    bool HasBeaconUuid() const;\n    const char *BeaconUuid() const;\n\n    bool HasBeaconMajor() const;\n    uint16_t BeaconMajor() const;\n\n    bool HasBeaconMinor() const;\n    uint16_t BeaconMinor() const;\n\n    const char *BeaconAddress() const;\n    int BeaconRssi() const;\n', 'BadgeConfig beacon getters')
text = rep(text, '    char beaconAddress[18];\n    int beaconRssi;\n\n    void ResolveBeaconSettings();\n', '    char beaconAddress[18];\n    char beaconUuid[37];\n\n    bool beaconMajorDefined;\n    uint16_t beaconMajor;\n\n    bool beaconMinorDefined;\n    uint16_t beaconMinor;\n\n    int beaconRssi;\n\n    void ResolveBeaconSettings();\n', 'BadgeConfig beacon storage')
path.write_text(text, encoding='utf-8')

path = Path('BadgeConfig.cpp')
text = path.read_text(encoding='utf-8')
text = rep(text, "    beaconAddress[0] = '\\0';\n    beaconRssi = -75;\n\n    ResolveBeaconSettings();\n", "    beaconAddress[0] = '\\0';\n    beaconUuid[0] = '\\0';\n\n    beaconMajorDefined = false;\n    beaconMajor = 0;\n\n    beaconMinorDefined = false;\n    beaconMinor = 0;\n\n    beaconRssi = -75;\n\n    ResolveBeaconSettings();\n", 'BadgeConfig beacon defaults')
text = rep(text, "bool BadgeConfig::BeaconWatchEnabled() const\n{\n    return beaconAddress[0] != '\\0';\n}\n\nconst char *BadgeConfig::BeaconAddress() const\n{\n    return beaconAddress;\n}\n\nint BadgeConfig::BeaconRssi() const\n", "bool BadgeConfig::BeaconWatchEnabled() const\n{\n    return\n        beaconUuid[0] != '\\0' ||\n        beaconAddress[0] != '\\0';\n}\n\nbool BadgeConfig::HasBeaconUuid() const\n{\n    return beaconUuid[0] != '\\0';\n}\n\nconst char *BadgeConfig::BeaconUuid() const\n{\n    return beaconUuid;\n}\n\nbool BadgeConfig::HasBeaconMajor() const\n{\n    return beaconMajorDefined;\n}\n\nuint16_t BadgeConfig::BeaconMajor() const\n{\n    return beaconMajor;\n}\n\nbool BadgeConfig::HasBeaconMinor() const\n{\n    return beaconMinorDefined;\n}\n\nuint16_t BadgeConfig::BeaconMinor() const\n{\n    return beaconMinor;\n}\n\nconst char *BadgeConfig::BeaconAddress() const\n{\n    return beaconAddress;\n}\n\nint BadgeConfig::BeaconRssi() const\n", 'BadgeConfig beacon getter implementations')
text = rep(text, '    else if (strcmp(key, "BEACON_ADDRESS") == 0)\n    {\n        if (strlen(value) != 17)\n        {\n            return false;\n        }\n\n        snprintf(\n            beaconAddress,\n            sizeof(beaconAddress),\n            "%s",\n            value);\n\n        return true;\n    }\n    else if (strcmp(key, "BEACON_RSSI") == 0)\n', '    else if (strcmp(key, "BEACON_UUID") == 0)\n    {\n        if (strlen(value) != 36)\n        {\n            return false;\n        }\n\n        snprintf(\n            beaconUuid,\n            sizeof(beaconUuid),\n            "%s",\n            value);\n\n        return true;\n    }\n    else if (strcmp(key, "BEACON_MAJOR") == 0)\n    {\n        char *end = nullptr;\n\n        unsigned long parsed =\n            strtoul(\n                value,\n                &end,\n                10);\n\n        if (end == value ||\n            *end != \'\\0\' ||\n            parsed > 65535)\n        {\n            return false;\n        }\n\n        beaconMajor =\n            static_cast<uint16_t>(parsed);\n\n        beaconMajorDefined = true;\n        return true;\n    }\n    else if (strcmp(key, "BEACON_MINOR") == 0)\n    {\n        char *end = nullptr;\n\n        unsigned long parsed =\n            strtoul(\n                value,\n                &end,\n                10);\n\n        if (end == value ||\n            *end != \'\\0\' ||\n            parsed > 65535)\n        {\n            return false;\n        }\n\n        beaconMinor =\n            static_cast<uint16_t>(parsed);\n\n        beaconMinorDefined = true;\n        return true;\n    }\n    else if (strcmp(key, "BEACON_ADDRESS") == 0)\n    {\n        if (strlen(value) != 17)\n        {\n            return false;\n        }\n\n        snprintf(\n            beaconAddress,\n            sizeof(beaconAddress),\n            "%s",\n            value);\n\n        return true;\n    }\n    else if (strcmp(key, "BEACON_RSSI") == 0)\n', 'iBeacon configuration keys')
path.write_text(text, encoding='utf-8')

path = Path('BleRadar.h')
text = path.read_text(encoding='utf-8')
text = rep(text, '    bool FindAddress(\n        const char *targetAddress,\n        int minimumRssi,\n        uint32_t seconds,\n        int &foundRssi);\n\n    int Count() const;\n', '    bool FindAddress(\n        const char *targetAddress,\n        int minimumRssi,\n        uint32_t seconds,\n        int &foundRssi);\n\n    bool FindIBeacon(\n        const char *targetUuid,\n        bool matchMajor,\n        uint16_t targetMajor,\n        bool matchMinor,\n        uint16_t targetMinor,\n        int minimumRssi,\n        uint32_t seconds,\n        int &foundRssi);\n\n    int Count() const;\n', 'BleRadar iBeacon declaration')
path.write_text(text, encoding='utf-8')

path = Path('BleRadar.cpp')
text = path.read_text(encoding='utf-8')
text = rep(text, 'int BleRadar::Count() const\n{', 'bool BleRadar::FindIBeacon(\n    const char *targetUuid,\n    bool matchMajor,\n    uint16_t targetMajor,\n    bool matchMinor,\n    uint16_t targetMinor,\n    int minimumRssi,\n    uint32_t seconds,\n    int &foundRssi)\n{\n    foundRssi = -127;\n\n    if (targetUuid == nullptr ||\n        targetUuid[0] == \'\\0\')\n    {\n        return false;\n    }\n\n    Serial.printf(\n        "BEACON WATCH: passive iBeacon scan for UUID %s.\\n",\n        targetUuid);\n\n    if (!BLEDevice::getInitialized())\n    {\n        BLEDevice::init("");\n    }\n\n    BLEScan *scanner =\n        BLEDevice::getScan();\n\n    if (scanner == nullptr)\n    {\n        Serial.println(\n            "BEACON WATCH: unable to get BLE scanner.");\n\n        BLEDevice::deinit(false);\n        return false;\n    }\n\n    scanner->clearResults();\n    scanner->setActiveScan(false);\n    scanner->setInterval(100);\n    scanner->setWindow(99);\n\n    BLEScanResults results =\n        scanner->start(\n            seconds,\n            false);\n\n    bool found = false;\n\n    for (int i = 0;\n         i < results.getCount();\n         i++)\n    {\n        BLEAdvertisedDevice advertised =\n            results.getDevice(i);\n\n        if (!advertised.haveManufacturerData())\n        {\n            continue;\n        }\n\n        std::string manufacturerData =\n            advertised.getManufacturerData();\n\n        if (!IsIBeaconData(\n                manufacturerData))\n        {\n            continue;\n        }\n\n        BleRadarDevice candidate;\n\n        memset(\n            &candidate,\n            0,\n            sizeof(candidate));\n\n        ParseIBeacon(\n            manufacturerData,\n            candidate);\n\n        if (strcasecmp(\n                candidate.BeaconUuid,\n                targetUuid) != 0)\n        {\n            continue;\n        }\n\n        if (matchMajor &&\n            candidate.BeaconMajor != targetMajor)\n        {\n            continue;\n        }\n\n        if (matchMinor &&\n            candidate.BeaconMinor != targetMinor)\n        {\n            continue;\n        }\n\n        foundRssi =\n            advertised.getRSSI();\n\n        found =\n            foundRssi >= minimumRssi;\n\n        Serial.printf(\n            "BEACON WATCH: iBeacon UUID=%s major=%u minor=%u RSSI=%d threshold=%d accepted=%s.\\n",\n            candidate.BeaconUuid,\n            candidate.BeaconMajor,\n            candidate.BeaconMinor,\n            foundRssi,\n            minimumRssi,\n            found ? "yes" : "no");\n\n        break;\n    }\n\n    scanner->clearResults();\n    BLEDevice::deinit(false);\n\n    if (!found)\n    {\n        Serial.println(\n            "BEACON WATCH: target iBeacon not present.");\n    }\n\n    return found;\n}\n\nint BleRadar::Count() const\n{', 'BleRadar iBeacon implementation')
path.write_text(text, encoding='utf-8')

path = Path('main.ino')
text = path.read_text(encoding='utf-8')
text = rep(text, '    constexpr uint64_t BeaconTimerWakeMicroseconds =\n        60ULL * 1000000ULL;\n}\n\nnamespace BeaconWatch\n{\n    constexpr uint32_t ScanSeconds = 2;\n\n    constexpr int PresentConfirmations = 2;\n    constexpr int GoneConfirmations = 3;\n}\n', '    constexpr uint64_t BeaconTimerWakeMicroseconds =\n        30ULL * 1000000ULL;\n}\n\nnamespace BeaconWatch\n{\n    constexpr uint32_t ScanSeconds = 3;\n\n    constexpr int PresentConfirmations = 1;\n    constexpr int GoneConfirmations = 3;\n}\n', 'Beacon Watch timing')
text = rep(text, '    bool found =\n        bleRadar.FindAddress(\n            badgeConfig.BeaconAddress(),\n            badgeConfig.BeaconRssi(),\n            BeaconWatch::ScanSeconds,\n            foundRssi);\n', '    bool found = false;\n\n    if (badgeConfig.HasBeaconUuid())\n    {\n        found =\n            bleRadar.FindIBeacon(\n                badgeConfig.BeaconUuid(),\n                badgeConfig.HasBeaconMajor(),\n                badgeConfig.BeaconMajor(),\n                badgeConfig.HasBeaconMinor(),\n                badgeConfig.BeaconMinor(),\n                badgeConfig.BeaconRssi(),\n                BeaconWatch::ScanSeconds,\n                foundRssi);\n    }\n    else\n    {\n        found =\n            bleRadar.FindAddress(\n                badgeConfig.BeaconAddress(),\n                badgeConfig.BeaconRssi(),\n                BeaconWatch::ScanSeconds,\n                foundRssi);\n    }\n', 'Beacon Watch target selection')
path.write_text(text, encoding='utf-8')

print('Dual-target Beacon Watch patch applied.')
